# Generated by Django 5.2.8 on 2025-11-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
